---
title: "Untitled"
output: html_document
date: "2022-10-20"
---

Blank Rmd for debugging and troubleshooting

```{r}
as.Date(paste(format(Sys.Date(), "%Y-%m"), 1, sep="-"), "%Y-%m-%d")
as.Date("2022-12-01")
t.data_coverage_source = df1 %>%
  rbind(df2 %>% rename(n_id_distinct=n_distinct)) %>%
  as.data.frame() %>%   
  mutate(date_ym_reformat = ifelse(str_detect(date_ym,"-"),1,ifelse(date_ym=="","",0))) %>%
  mutate(date_ym = ifelse(date_ym_reformat==0,str_pad(date_ym,6,side="left",pad=0),date_ym)) %>%
  mutate(date_ym = ifelse(date_ym_reformat==0,paste0(substr(date_ym,1,4),"-",substr(date_ym,5,6)),date_ym)) %>%
  select(-date_ym_reformat)

t.data_coverage = t.data_coverage_source %>%
  mutate(date_ym = ifelse(date_ym=="", NA, date_ym)) %>% 
  #remove null dates
  filter(!is.na(date_ym)) %>% 
  separate(date_ym, c("date_y", "date_m"), remove=FALSE, sep = '-') %>% 
  mutate(across(.cols = c(date_y, date_m), .fn = ~ as.numeric(.))) %>% 
  #remove future dates > this year + 1 (to reduce file size)
  filter(date_y <= (as.numeric(format(Sys.Date(), "%Y"))+1)) %>% 
  #expand to include all dates in between where counts=0
  group_by(dataset) %>%
  expand(date_y=min(date_y):max(date_y),date_m=1:12) %>%
  ungroup() %>%
  mutate(date_ym = paste0(str_pad(date_y,width=4,pad=0,side="left"),
                          "-",
                          str_pad(date_m,width=2,pad=0,side="left"))) %>% 
  left_join(t.data_coverage_source, by = c("date_ym","dataset")) %>%
  mutate(across(.cols = starts_with('n'),
                .fn = ~ replace_na(.,0))) %>%
  group_by(dataset) %>%
  arrange(dataset,date_y,date_m) %>%
  mutate(across(.cols = starts_with("n"),
                .names = "{.col}_cum",
                .fn = ~ cumsum(.))) %>% 
  filter(!if_all(ends_with("cum"), ~ . == 0)) %>% 
  select(!ends_with("cum")) %>%
  #date month names for plot annotation
  mutate(date_name = paste0(month.name[date_m]," ", date_y, ": ")) %>%
  mutate(date_name_season = paste0(date_y, ": ")) %>%
  mutate(date_m_name = paste0(month.name[date_m])) %>%
  pivot_longer(cols=starts_with("n"), names_to="Type",values_to="N") %>%
  mutate(date_format = as.Date(paste(date_ym, 1, sep="-"), "%Y-%m-%d"))


t.data_coverage %>%
  filter(str_detect(dataset,"hes_apc_all_years")) %>%
  arrange(desc(date_y)) %>%
  write.table("test.txt")




  
```



```{r}


coverage_data_all_records =  
        t.data_coverage %>%
          left_join(datasets_available,by = c("dataset"="Dataset")) %>%
          filter(dataset=="Welsh Longitudinal General Practice") %>%
          #tooltips for plot
          mutate(N_tooltip = format(.data$N, nsmall=0, big.mark=",", trim=TRUE)) %>%
          mutate(N_tooltip_date = paste0(date_name,N_tooltip)) %>%
          mutate(N_tooltip_date_season = paste0(date_name,N_tooltip)) #date_name_season
        
     
      
      season_colour_palette = reactive({setNames(
        rep(rev(colour_stepped_palette), length.out=nrow(distinct(coverage_data_all_records(),date_y))),
        rev(pull(distinct(coverage_data_all_records(),date_y),date_y))
      )})

        coverage_data_start_date =
            reactive({
              coverage_data_all_records() %>%
                #filter date range
                mutate(start_date = as.Date(paste(start_date, 1, sep="-"), "%Y-%m-%d")) %>%
                filter(!start_date > date_format) %>%
                #using current month but this should be updated to use production ym in future
                mutate(current_date = as.Date(paste(format(Sys.Date(), "%Y-%m"), 1, sep="-"), "%Y-%m-%d")) %>%
                filter(date_format <= current_date)
              })

      coverage_data = reactive({
        if(input$all_records) {
          (coverage_data_all_records())
        } else {
          (coverage_data_start_date())
        }
      })

      date_range_coverage_extremum = reactive({
        coverage_data() %>%
        summarise(min = min(.data$date_y),
                  max = max(.data$date_y)) %>%
          pivot_longer(cols=c(min,max),names_to="extremum",values_to="year")
      })

      date_range_coverage_min = reactive({date_range_coverage_extremum() %>% filter(.data$extremum=="min") %>% pull(year)})
      date_range_coverage_max = reactive({date_range_coverage_extremum() %>% filter(.data$extremum=="max") %>% pull(year)})
      
      date_range_coverage_extremum_start_date = reactive({
        coverage_data_start_date() %>%
          summarise(min = min(.data$date_y),
                    max = max(.data$date_y)) %>%
          pivot_longer(cols=c(min,max),names_to="extremum",values_to="year")
      })
      
      date_range_coverage_min_start_date = reactive({date_range_coverage_extremum_start_date() %>% filter(.data$extremum=="min") %>% pull(year)})
      date_range_coverage_max_start_date = reactive({date_range_coverage_extremum_start_date() %>% filter(.data$extremum=="max") %>% pull(year)})

      observe({
        updateSliderInput(session, "date_range_coverage",
                          min = date_range_coverage_min(),
                          max = date_range_coverage_max(),
                          value = c(
                            date_range_coverage_min_start_date(),
                            date_range_coverage_max_start_date()
                          ),
                          step=1
                          )
        })
      
    
      #date filtered dataset
      coverage_data_filtered = reactive({
        coverage_data() %>%
          filter(.data$date_y>=input$date_range_coverage[1] & .data$date_y<=input$date_range_coverage[2]) %>%
          filter(Type %in% input$count_coverage)
      })
      
      coverage_data_filtered_season = reactive({
        coverage_data() %>%
          filter(.data$date_y>=input$date_range_coverage[1] & .data$date_y<=input$date_range_coverage[2]) %>%
          filter(Type %in% input$count_coverage_season)
      })

      


```


```{r}
compare_palette
state = state %>% 
  mutate(colors = c(colors_memory,rep(NA,(nrow(state)-length(colors_memory))))) %>%
  mutate(colors = ifelse(is.na(colors), setdiff(compare_palette,filter(state,!is.na(colors))$colors)[1], colors))


state = state %>% 
  mutate(colors = c(colors_memory,rep(NA,(nrow(state)-length(colors_memory))))) %>%
  mutate(colors = ifelse(is.na(colors), setdiff(compare_palette,filter(state,!is.na(colors))$colors)[1], colors))


t.data_dictionaryScot%>%
  mutate(field=stringr::str_to_lower(field))


tibble(
            count_options=c("Records","Records with a de-identified PERSON ID","Distinct de-identified PERSON ID"),
            count_options_1=c("Records","Records with a \nde-identified PERSON ID","Distinct \nde-identified PERSON ID")
            )


update_date = as.Date("2023-06-15")
update_date_string = paste(months(update_date),lubridate::year(update_date))


t.dataset_overview_wales  %>% rename(n_id_distinct = n_distinct) %>%
            mutate(archived_on = as.Date( archived_on, tryFormats = c("%d/%m/%Y")))

```



```{r}
completeness_data =
t.dataset_completeness %>%
          filter(dataset == "gdppr") %>%
          mutate(column_name = trimws(column_name)) %>%
          mutate(completeness = round(completeness*100,2)) %>%
          arrange(desc(completeness),column_name)
      
      colour_palette = ({completeness_data %>% 
        distinct(completeness) %>% bind_cols(
          tibble(colours = colorCompleteness(nrow(completeness_data %>% distinct(completeness))))) %>%
        left_join(select(completeness_data,c(completeness,column_name)),by = "completeness")})
      

      
      
      
      
      
      
      
t.data_dictionaryEng %>%
            select("table") %>%
            left_join(select(datasets_available, c("table","Dataset","Title","title_dataset","dataset_dataset")),
                      by=c("table")) %>%
            filter(Dataset == "gdppr") %>%
            select(-Dataset) %>%
            distinct() %>%
            mutate(Dataset = title_dataset) %>%
            select(-Title,-title_dataset) %>%
            select(where(not_all_na)) %>%
            left_join(t.data_dictionaryEng, by = "table") %>%
            select(-table,-database,-dataset_dataset,-path)

```






```{r}



data_dict = ({

          t.data_dictionaryScot %>% 
            left_join(select(datasets_available, c("table","Dataset")), by=c("table"))  %>%
            filter(table == "COVID Tests") %>%
            select(-table) 
          

        
      })

      
             t.dataset_completeness = t.dataset_completeness_scotland
      ##########################################################################
      completeness_data = ({

        t.dataset_completeness %>%
          filter(dataset == "ecoss") %>%
          mutate(column_name = trimws(column_name)) %>%
          mutate(completeness = round(completeness*100,2)) %>%
          arrange(desc(completeness),column_name)
          #left_join(dataset_names())
        
      })
      
      
        dataset_names = ({(
        t.dataset_dashboard %>%
          filter(dataset_dataset == "ecoss") %>%
          select(dataset="dataset_dataset","Dataset"=title_dataset))
      })
      ##########################################################################
      
      #colour gradient
      colorCompleteness = colorRampPalette(compare_colours)
      
      color_data = ({completeness_data %>%
          distinct(completeness) %>% bind_cols(
            tibble(colours = colorCompleteness(nrow(completeness_data %>% distinct(completeness))))) %>%
          left_join(select(completeness_data,c(completeness,column_name,dataset)),by = "completeness") %>%
          left_join(dataset_names)
        })
      
      
      ##########################################################################
        
          
          my_data = ({
              
              data_dict %>%
                rename_with(str_to_title) %>%
                left_join((color_data%>%select(-Dataset)%>%rename(Dataset=dataset)), by=c("Dataset"="Dataset","Field"="column_name")) %>%
                select(-Dataset) %>%
                distinct() %>%
                mutate(Position = row_number())
                #mutate(Dataset = ifelse(Title==Title_dataset, NA, Title_dataset)) %>%
                #select(where(not_all_na)) %>%
              
            }



color_data%>%select(-Dataset)%>%rename(Dataset=dataset)

```





```{r}

 dataset_names = ({
        t.dataset_dashboard %>%
          filter(dataset_dataset == "iapt_care_activities_all_years") %>%
          select(dataset="dataset_dataset","Dataset"=title_dataset)
      })
      

data_dict = ({

          t.data_dictionaryEng %>%
            select("table") %>%
            left_join(select(datasets_available, c("table","Dataset","Title","title_dataset","dataset_dataset")),
                      by=c("table")) %>%
            filter(Dataset == "iapt_care_activities_all_years") %>%
            select(-Dataset) %>%
            mutate(Dataset = title_dataset) %>%
            distinct() %>%
            #select(-Title,-title_dataset) %>%
            left_join(t.data_dictionaryEng, by = "table") %>%
            select(-table,-database,-dataset_dataset,-path) #-x
        
        
      })
      

      t.dataset_completeness = t.dataset_completeness_eng
      ##########################################################################
      completeness_data = ({

        t.dataset_completeness %>%
          filter(dataset == "iapt_care_activities_all_years") %>%
          mutate(column_name = trimws(column_name)) %>%
          mutate(completeness = round(completeness*100,2)) %>%
          arrange(desc(completeness),column_name)
          #left_join(dataset_names())
        
      })
      
      
      ##########################################################################
      
      #colour gradient
      colorCompleteness = colorRampPalette(compare_colours)
      
      color_data = ({completeness_data %>%
          distinct(completeness) %>% bind_cols(
            tibble(colours = colorCompleteness(nrow(completeness_data %>% distinct(completeness))))) %>%
          left_join(select(completeness_data,c(completeness,column_name,dataset)),by = "completeness") %>%
          left_join(dataset_names)
        })
      
      
      ##########################################################################
        
          
          my_data = ({

              data_dict %>%
                rename_with(str_to_title) %>%
                mutate(Position = row_number()) %>%
                relocate(Position) %>%
                left_join(color_data, by=c("Dataset"="Dataset","Field"="column_name")) %>%
                select(-Dataset) %>%
                #mutate(Dataset = ifelse(Title==Title_dataset, NA, Title_dataset)) %>%
                #select(where(not_all_na)) %>%
                select(-Title,-Title_dataset,-dataset)


          })
      

 
```

```{r}

paste0(format(99, nsmall=0, big.mark=",", trim=FALSE),"%")


paste(sprintf("%5.1f", 100))
paste(sprintf("%5.1f%%", 99.2))
paste(sprintf("%5.1f%%", 5.12))
```

